{{- if and .Values.config.authKey.enabled .Values.config.authKey.key }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "golink.fullname" . }}
  labels:
    {{- include "golink.labels" . | nindent 4 }}
stringData:
  {{ .Values.config.authKey.keyName }}: {{ .Values.config.authKey.key }}
{{- end }}
