name: Publish chart

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - name: Package the chart
        run: helm package .
      - name: Login to GHCR
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push chart to GHCR
        run: helm push golink-$(yq .version Chart.yaml).tgz oci://ghcr.io/${{ github.repository }}
